### PR TITLE
changed to satisfy some KLC rules

### PR DESCRIPTION
**Pull request by michal777**
Rotated and moved, added courtyard, set positions of reference and value, fixed \r instead of \n.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Why is there no courtyard clearance?

**Comment by michal777** [comment]
I tried to draw it as Lorenzo Marcantonio wrote on mailing list
"0.25 clearance is the common IPC value for SMD component, measured from the pad edges and then enlarged to enclose the silkscreen drawings".
This is not SMD library, but I don't know any rules for THT. Should the clearance be the same for pads and silkscreen? What value should be used for THT?
It's not specified in rule 6.6 :(

**Comment by CarlPoirier** [comment]
Good point there, Michal. The KLC does not address this.

In our reference document, "PCB Design Optimization starts in the CAD library", it says "Placement Courtyard for most Connectors is 20 mil (0.5 mm)".

I suggest you go with this for now, but I am starting a discussion on the mailing list on the matter. If no one objects, I will amend it to the KLC.

**Comment by michal777** [comment]
The rule 6.6 is not clear for me. I've posted some questions and suggestions on mailing list.

**Comment by CarlPoirier** [comment]
Thank you Michal. Let's hold this for now.

**Comment by michal777** [comment]
Next change - 1-pin mark visible after assembly. Courtyard 0.5 mm. Is it ready to merge?

**Comment by CarlPoirier** [comment]
Hi Michal,

Sorry for not getting back to this. It looks great, thanks!

**Pull request merged**
