### PR TITLE
Added footprints for 2mm socket strips 

### PR DESCRIPTION
**Pull request by SchrodingersGat**
(downloaded from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm)

These footprints are shared under CC

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Same issues as in KiCad/Pin_Headers.pretty#10

**Comment by SchrodingersGat** [comment]
Footprints have been renamed to match convention, and run against check_kicad_mod

**Comment by ricardocrudo** [comment]
Hello @SchrodingersGat 

The footprints still having some issues:
* Silkscreen is superposing pads
* Courtyard line is missing
* Anchor is not set at pin 1

Also would be nice if the silkscreen look like with already existing ones.

Thanks

**Comment by SchrodingersGat** [comment]
Anchor now set at pin 1
Silkscreen issues fixed
Flipped footprints along horizontal axis to match the 2.54mm pitch sockets already in the library

**Comment by SchrodingersGat** [comment]
Bump

**Comment by CarlPoirier** [comment]
test this please

**Comment by SchrodingersGat** [comment]
Hi @CarlPoirier - Same as for the Pin Headers, I have completely re-generated the 2.00mm pin headers in 1x and 2x row configurations.

Layout and silkscreen have been designed to match the 2.54mm headers.

Please let me know if these need any more adjustments. They are all meeting KLC currently

**Comment by SchrodingersGat** [comment]
@CarlPoirier as with the Pin-Headers I have re-added the 3D model references:

3D models are here - https://github.com/KiCad/kicad-library/pull/401

**Comment by SchrodingersGat** [comment]
@ricardocrudo these have been re-generated and changed to match the 2.54mm pin headers

**Comment by SchrodingersGat** [comment]
Hey @ricardocrudo when you get a chance please check this out again. The footprints have been re-generated (script based rather than hand-made) and should meet all specs now. Thanks :)

**Comment by jkriege2** [comment]
Oh, didn't see that ... but this will be included here: https://github.com/KiCad/Socket_Strips.pretty/pull/6

**Comment by SchrodingersGat** [comment]
Alright I'll close this as it's very out of date

**Pull request closed without merging**
