### PR TITLE
Fixed SMD pad positions

### PR DESCRIPTION
**Pull request by svheymann**
Footprints on protoype PCBs dont match very well with real connectors.

Corrected SMD pad position according to TE, 3M, Amphenol and Harwin
documents, it should look like this:

http://www.mouser.com/ds/2/181/M50-310-350829.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
> Footprints on protoype PCBs dont match very well with real connectors.

What is the issue, specifically?

**Comment by svheymann** [comment]
The space between the two rows of pads is too large. It should be 1.5mm, not >2.5mm.

**Comment by SchrodingersGat** [comment]
Ok, got it. Thanks :)

@jkriege2 I believe you scripted these - was there a reason the pads are so far apart? If there is no good reason I will merge this PR.

**Comment by jkriege2** [comment]
Hi!

yup, seems like a typo when scripting ;-)

Thanks for spotting!
JAN

**Comment by SchrodingersGat** [comment]
Thanks @svheymann :)

**Pull request merged**
